server:
  port: 8090
#  servlet:
#      context-path: /emos-api
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: user
      password: 123456
    oauth2:
      resourceserver:
        jwt:
          audiences:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: 123456
      initial-size: 2
      max-active: 4
      min-idle: 4
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        wall:
          config:
            condition-op-xor-allow:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
#      authentication-database: articledb
#      username: admin
#      password: 123456

    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-active: 1000
          max-wait: -1ms
          max-idle: 16
          min-idle: 8

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
wx:
#  appid: wx3a1be64c1bcd63be
#  app-secret: 75ad3359ef585566daf010d06ada1d78
  get-openid-url: https://api.weixin.qq.com/sns/jscode2session

token:
  expire: 30
emos:
  image-folder: /Users/simo/Java/imooc/image